# This file can be used to start multiple containers supporting the SOLA Systematic Registration solution. Use the command
# docker-compose up -d. It will take up to 3 minutes before the SOLA Systematic Registration services can be accessed.
version: '3'

networks:
    sola_sr:

volumes:
   sola_sr_data:
      driver: local

services:
    db:
        # DB server hosting SOLA SR database. To connect to this db; hostname=database, user=postgres, passwd=sola
        image: mcdowella/sola-systemreg-db
        ports:
         - "5432:5432"
        container_name: sr-db
        environment:
          POSTGRES_PASSWORD: sola
          CREATE_SOLA_DB: y
          SOLA_LOAD_DATA: y
        networks:
           sola_sr:
               aliases:
                 - database
        volumes:
         - sola_sr_data:/var/lib/postgresql/data

    server:
        image: mcdowella/sola-systemreg-server
        container_name: sr-srv
        ports:
         - "4848:4848"
         - "8080:8080"
         - "8181:8181"
        depends_on:
         - db
        environment:
          WAIT_TIME: 180
        networks:
           sola_sr:

    # Container that deploys pgAdmin4 to allow administration of the SOLA database. Accessible on localhost:80
    # with username=db@flossola.org and passwd=sola
    dbadmin:
        image: dpage/pgadmin4
        container_name: db-admin
        ports:
          - "80:80"
        environment:
           PGADMIN_DEFAULT_EMAIL: db@flossola.org
           PGADMIN_DEFAULT_PASSWORD: sola
        networks:
           sola_sr:

    sys-backups:
        image: prodrigestivill/postgres-backup-local
        container_name: sola-db-backups
        restart: always
        volumes:
           - $HOME/sola-docker-data/backups/pg-sys:/backups
        links:
           - db
        environment:
          - POSTGRES_HOST=192.168.1.71
          - POSTGRES_DB=sola
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=sola
          - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
          - SCHEDULE=@daily
          - BACKUP_KEEP_DAYS=7
          - BACKUP_KEEP_WEEKS=4
          - BACKUP_KEEP_MONTHS=6
          - HEALTHCHECK_PORT=85
        networks:
           sola_sr:
